version: '3.8'

services:
  web:
    build: .
    ports:
      - "50000:5000"
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

