[tool.poetry]
name = "genai-api-calling"
version = "0.1.0"
description = ""
authors = ["CT Wu"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
jupyter = "^1.0.0"
google-generativeai = "^0.7.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
